<div class="container">
    <div class="mt-4">
        <h4 class="text-danger">You need to setup your homepage first!</h4>

        <p><strong>1. Go to Admin -> Plugins then activate all plugins.</strong></p>
        <p><strong>2. Go to Admin -> Pages and create a page:</strong></p>

        <div class="mt-2">
            <div>- Content:</div>
            <pre class="my-2 bg-black text-light p-2 rounded"><code>[hero-banner title="Business Consulting All Solutions" subtitle="WE ARE EXPERT IN THIS FIELD" description="Apexa Helps You To Convert Your Data Into A Strategic Asset And Get Business Insights Apexa Helps You To Convert Your Data Into Asset And Get Top-Notch Business Insights." button_label="Read more" button_url="/" display_social_links="0,1" display_button_scroll_down="0,1" background_image="backgrounds/hero-banner.jpg" background_color="transparent" enable_lazy_loading="no"][/hero-banner]
[brands name_1="Door Dash" image_1="brands/1.png" url_1="/" name_2="Discord" image_2="brands/2.png" url_2="/" name_3="Airbnb" image_3="brands/3.png" url_3="/" name_4="Norton" image_4="brands/4.png" url_4="/" name_5="Naturewave" image_5="brands/5.png" url_5="/" quantity="5" background_color="transparent"][/brands]
[about-us-information style="style-1" title="We Help Organizations To Make Ultimate Businesses Growth Success." subtitle="SIMPLY KNOW ABOUT" description="We successfully cope with tasks of varying complexity, provide long-term guarantees and regularly master new Practice Area technologies. Our portfolio includes dozens." image="general/about-us-information-1.jpg" quantity="2" title_1="Business Solutions" description_1="Semper egetuis tellus urna condi" icon_1="ti ti-target" title_2="Quality Services" description_2="Semper egetuis tellus urna condi" icon_2="ti ti-chart-bar" data_count="25 -" data_count_description="Years Of - Experience" author_name="Martinaze" author_title="CEO" author_avatar="general/author-avatar.png" author_signature="general/author-signature.png" button_label="Read more" button_url="/" background_color="transparent" enable_lazy_loading="yes"][/about-us-information]
[services style="style-1" title="We Offer An Effective Wide Area Business solutions" subtitle="WHAT WE OFFER" description="Empowering Businesses through Strategic Consulting With Us" service_ids="1,2,3,4" button_label="See All Services" button_url="/" background_image="backgrounds/services-bg.jpg" background_color="transparent" enable_lazy_loading="yes"][/services]
[about-us-information style="style-8" title="We Offer Business Insight World Class Consulting" subtitle="WHY WE ARE THE BEST" description="We successfully cope with tasks of varying complexity provide area longerty guarantees and regularly master new Practice Following gies heur portfolio includes dozen." image="general/about-us-information-8-1.jpg" image_1="general/about-us-information-8-2.jpg" quantity="2" title_1="Business Solutions" description_1="Semper egetuis kelly for tellus urna area condition." icon_1="ti ti-chart-pie-2" title_2="Market Analysis" description_2="Semper egetuis kelly for tellus urna area condition." icon_2="ti ti-broadcast" background_color="rgb(23, 26, 124)" enable_lazy_loading="yes"][/about-us-information]
[site-statistics style="style-1" quantity="4" title_1="Successfully Completed Projects" data_1="45" unit_1="+" image_1="icons/trophy.png" title_2="Satisfied 100% Our Clients" data_2="92" unit_2="K" image_2="icons/star.png" title_3="All Over The World We Are Available" data_3="19" unit_3="+" image_3="icons/popularity.png" title_4="Years of Experiences To Run This Company" data_4="25" unit_4="+" image_4="icons/time.png" background_image="backgrounds/site-statistics-bg.png" background_color="rgb(255, 251, 243)" enable_lazy_loading="yes"][/site-statistics]
[projects style="style-1" title="Let’s Discover All Our Clients Recent Project" subtitle="OUR PROJECTS" description="We successfully cope with tasks of varying complexity, <br> provide long-term guarantees and regularly" project_ids="1,2,3,4" button_label="See All Projects" button_url="/" background_color="transparent" enable_lazy_loading="yes"][/projects]
[contact-block style="style-1" title="Offering The Best Experience Of Business Consulting Services" subtitle="Toll Free Call" phone_number="+ 88 ( 9600 ) 6002" button_label="Request a Free Call" button_url="tel:8896006002" background_image="backgrounds/contact-block-bg.jpg" background_color="transparent" enable_lazy_loading="yes"][/contact-block]
[team style="style-1" title="Financial Expertise You Can Trust" subtitle="MEET OUR TEAM" description="Our power of choice is untrammelled and when nothing prevents being able to do what we like best every pleasure." team_ids="1,2,3,4" background_color="transparent" enable_lazy_loading="yes"][/team]
[consulting-block title="Trusted , Happy & Satisfied Businesses" description="When you work with HR Solutions, you get the best. We provide adaptable solutions that allow you to be a part of the entire process" image="general/consulting-block.jpg" data_count="40+" data_count_description="Consulting <br> farm" background_color="rgb(25, 29, 136)"][/consulting-block]
[testimonials style="style-1" image="general/testimonials-1.png" testimonial_ids="1,2,3,4" background_color="rgb(255, 251, 243)" enable_lazy_loading="yes"][/testimonials]
[blog-posts style="style-1" category_ids="2,3,4,5" title="Featured News And Insights" subtitle="OUR BLOG UPDATE" limit="3" background_image="backgrounds/blog-posts-bg.jpg" background_color="transparent" enable_lazy_loading="yes"][/blog-posts]</code></pre>
            <br>
            <div>- Template: <strong>Homepage</strong>.</div>
        </div>

        <p><strong>3. Then go to Admin -> Appearance -> Theme options -> Page to set your homepage.</strong></p>
    </div>
</div>